language: python
matrix:
  include:
    - python: 3.7
      dist: bionic
      sudo: true
before_install:
  - pip install pipenv
install:
  - pipenv install -e . --skip-lock
  - pipenv install -d --skip-lock
script:
  - pipenv run mypy typedjson
  - pipenv run yapf -r typedjson -d
  - pipenv run pytest
